version: "3.8"
name: menu-bot-infra
services:
  postgres:
    image: postgres:16-alpine
    container_name: menu-bot-postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"